FROM python:3.12

RUN apt-get update && \
apt-get install -y build-essential tar wget && \
pip install uv && \
rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY pyproject.toml ./

RUN uv venv && \
    uv pip install -r pyproject.toml

COPY . .

EXPOSE 5333
CMD ["uv", "run", "python", "main.py"]