FROM python:3.12

RUN apt-get update && \
    apt-get install -y build-essential tar wget && \
    pip install uv && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY . .

# Install dependencies directly
RUN uv pip install django>=5.2.5 pytest>=7.0.0

EXPOSE 5333
CMD ["python", "main.py"]